spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    initialize: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: uberappnwt@gmail.com
    password: dhkfvtxpmjqgwgli
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  social:
    facebook:
      app-id: 876191489714176
      app-secret: 10a1cef3a11829c3526dda676d78b667
    google:
      app-id: 580010731527-g2pjimi8f9u1q1apl9urmfsse1birc6m.apps.googleusercontent.com
      app-secret: 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

##spring.datasource.url=jdbc:h2:file:/data/demo
#spring.datasource.initialize=true
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
##https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
##spring.jpa.open-in-view=true

##spring.mvc.view.prefix:/WEB-INF/jsp/
##spring.mvc.view.suffix:.jsp