export interface Driver {
    firstName: string,
    lastName: string, 
    email: string,
    password: string, 
    phone_number: string,
    country: string,
    street: string,
    city: string,
    vehicleTypeId: number,
    vehicleMake: string, 
    vehicleModel: string, 
    license_plate_number: string,
    makeYear: number,
    petsAllowed: boolean,
    babiesAllowed: boolean,
}